spring:
  application:
    name: "platform-or-managing-a-hotel-business"
  datasource:
    url: jdbc:postgresql://93.93.207.141:5432/hotel
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
