spring:
  application:
    name: "platform-or-managing-a-hotel-business"
  datasource:
    url: //??????? ?? ??????????? ??
    username: //???????? ?? ???????????? ????????????
    password: //???????? ?? ????????? ??????
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

