spring:
  application:
    name: "platform-or-managing-a-hotel-business"
  datasource:
    url: jdbc:postgresql://93.93.207.141:5432/hotel
    username: postgres
    password: Dlc6dPcOLgaVqsJVRo1y9At9oPbaLlLbZDzv3DDn
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
